const url = [
    "https://image.ibb.co/ggXENy/9.jpg",
    "https://image.ibb.co/gUOcaJ/8.jpg",
    "https://image.ibb.co/bUDM2y/7.jpg",
    "https://image.ibb.co/eTKiFJ/6.jpg",
    "https://image.ibb.co/iLZuNy/54.jpg",
    "https://image.ibb.co/bJiX9d/53.jpg",
    "https://image.ibb.co/hhZHaJ/52.jpg",
    "https://image.ibb.co/mUqC9d/51.jpg",
    "https://image.ibb.co/d9qC9d/50.jpg",
    "https://image.ibb.co/nna12y/5.jpg",
    "https://image.ibb.co/iSjHaJ/49.jpg",
    "https://image.ibb.co/nfUHaJ/48.jpg",
    "https://image.ibb.co/dSRxaJ/47.jpg",
    "https://image.ibb.co/jjZiFJ/46.jpg",    
    "https://image.ibb.co/cT18hy/44.jpg",   
    "https://image.ibb.co/joQC9d/42.jpg",
    "https://image.ibb.co/efYzpd/41.jpg",
    "https://image.ibb.co/eyb8hy/40.jpg",
    "https://image.ibb.co/eyNQUd/4.jpg",
    "https://image.ibb.co/f9aOFJ/39.jpg",
    "https://image.ibb.co/fXVZNy/38.jpg",
    "https://image.ibb.co/dFAqvJ/37.jpg",
    "https://image.ibb.co/hbYAvJ/36.jpg",
    "https://image.ibb.co/hcKThy/35.jpg",
    "https://image.ibb.co/dv68hy/34.jpg",
    "https://image.ibb.co/hJJohy/33.jpg",
    "https://image.ibb.co/kYjThy/32.jpg",
    "https://image.ibb.co/m59uNy/31.jpg",
    "https://image.ibb.co/g50epd/30.jpg",
    "https://image.ibb.co/csuThy/3.jpg",
    "https://image.ibb.co/jq73FJ/29.jpg",
    "https://image.ibb.co/h2BfvJ/28.jpg",
    "https://image.ibb.co/mY1fvJ/27.jpg",
    "https://image.ibb.co/npDtFJ/26.jpg",
    "https://image.ibb.co/d5Jh9d/25.jpg",
    "https://image.ibb.co/irZdhy/24.jpg",
    "https://image.ibb.co/euuN9d/23.jpg",
    "https://image.ibb.co/kUy4Ny/22.jpg",
    "https://image.ibb.co/g0gfvJ/21.jpg",
    "https://image.ibb.co/h4otFJ/20.jpg",
    "https://image.ibb.co/fAb29d/2.jpg",
    "https://image.ibb.co/djXLvJ/19.jpg",
    "https://image.ibb.co/eYL7aJ/18.jpg",
    "https://image.ibb.co/d1Wr2y/17.jpg",
    "https://image.ibb.co/kVp0vJ/16.jpg",
    "https://image.ibb.co/dCPdhy/15.jpg",
    "https://image.ibb.co/eVKYFJ/14.jpg",
    "https://image.ibb.co/itFUpd/13.jpg",
    "https://image.ibb.co/mrVvUd/12.jpg",
    "https://image.ibb.co/cFJh9d/11.jpg",
    "https://image.ibb.co/mGBPNy/10.jpg",
    "https://image.ibb.co/btpdhy/1.jpg",
    "https://image.ibb.co/nMfZvJ/55.jpg",
    "https://image.ibb.co/jMH1hJ/56.jpg",                                                  
];

export default url;

// "https://image.ibb.co/e7YM2y/45.png",
// "https://image.ibb.co/nFDcaJ/43.png",