const url = [
    "https://image.ibb.co/ggXENy/9.jpg",
    "https://image.ibb.co/gUOcaJ/8.jpg",
    "https://image.ibb.co/bUDM2y/7.jpg",
    "https://image.ibb.co/eTKiFJ/6.jpg",
    "https://image.ibb.co/iLZuNy/54.jpg",
    "https://image.ibb.co/bJiX9d/53.jpg",
    "https://image.ibb.co/hhZHaJ/52.jpg",
    "https://image.ibb.co/mUqC9d/51.jpg",
    "https://image.ibb.co/d9qC9d/50.jpg",
    "https://image.ibb.co/nna12y/5.jpg",
    "https://image.ibb.co/iSjHaJ/49.jpg",
    "https://image.ibb.co/nfUHaJ/48.jpg",
    "https://image.ibb.co/dSRxaJ/47.jpg",
    "https://image.ibb.co/jjZiFJ/46.jpg",    
    "https://image.ibb.co/cT18hy/44.jpg",   
    "https://image.ibb.co/joQC9d/42.jpg",
    "https://image.ibb.co/efYzpd/41.jpg",
    "https://image.ibb.co/eyb8hy/40.jpg",
    "https://image.ibb.co/eyNQUd/4.jpg",
    "https://image.ibb.co/f9aOFJ/39.jpg",
    "https://image.ibb.co/fXVZNy/38.jpg",
    "https://image.ibb.co/dFAqvJ/37.jpg",
    "https://image.ibb.co/hbYAvJ/36.jpg",
    "https://image.ibb.co/hcKThy/35.jpg",
    "https://image.ibb.co/dv68hy/34.jpg",
    "https://image.ibb.co/hJJohy/33.jpg",
    "https://image.ibb.co/kYjThy/32.jpg",
    "https://image.ibb.co/m59uNy/31.jpg",
    "https://image.ibb.co/g50epd/30.jpg",
    "https://image.ibb.co/csuThy/3.jpg",
    "https://image.ibb.co/jq73FJ/29.jpg",
    "https://image.ibb.co/h2BfvJ/28.jpg",
    "https://image.ibb.co/mY1fvJ/27.jpg",
    "https://image.ibb.co/npDtFJ/26.jpg",
    "https://image.ibb.co/d5Jh9d/25.jpg",
    "https://image.ibb.co/irZdhy/24.jpg",
    "https://image.ibb.co/euuN9d/23.jpg",
    "https://image.ibb.co/kUy4Ny/22.jpg",
    "https://image.ibb.co/g0gfvJ/21.jpg",
    "https://image.ibb.co/h4otFJ/20.jpg",
    "https://image.ibb.co/fAb29d/2.jpg",
    "https://image.ibb.co/djXLvJ/19.jpg",
    "https://image.ibb.co/eYL7aJ/18.jpg",
    "https://image.ibb.co/d1Wr2y/17.jpg",
    "https://image.ibb.co/kVp0vJ/16.jpg",
    "https://image.ibb.co/dCPdhy/15.jpg",
    "https://image.ibb.co/eVKYFJ/14.jpg",
    "https://image.ibb.co/itFUpd/13.jpg",
    "https://image.ibb.co/mrVvUd/12.jpg",
    "https://image.ibb.co/cFJh9d/11.jpg",
    "https://image.ibb.co/mGBPNy/10.jpg",
    "https://image.ibb.co/btpdhy/1.jpg",
    "https://image.ibb.co/nMfZvJ/55.jpg",
    "https://image.ibb.co/jMH1hJ/56.jpg",                                                  
];

export default url;

// "https://image.ibb.co/e7YM2y/45.png",
// "https://image.ibb.co/nFDcaJ/43.png",

const urlDB = [
    {"url": "https://image.ibb.co/btpdhy/1.jpg", "category": "flowers", "x": "80", "y": "80", "year": 201703, "inStock": false},
    {"url": "https://image.ibb.co/fAb29d/2.jpg", "category": "landscapes", "x": "40", "y": "40", "year": 201608, "inStock": false},
    {"url": "https://image.ibb.co/csuThy/3.jpg", "category": "other", "x": "40", "y": "70", "year": 201809, "inStock": false},
    {"url": "https://image.ibb.co/eyNQUd/4.jpg", "category": "nightscapes", "x": "40", "y": "60", "year": 201606, "inStock": false},
    {"url": "https://image.ibb.co/nna12y/5.jpg", "category": "landscapes", "x": "60", "y": "50", "year": 201408, "inStock": false},
    {"url": "https://image.ibb.co/eTKiFJ/6.jpg", "category": "nightscapes", "x": "20", "y": "20", "year": 201602, "inStock": false},
    {"url": "https://image.ibb.co/bUDM2y/7.jpg", "category": "nightscapes", "x": "20", "y": "20", "year": 201602, "inStock": false},
    {"url": "https://image.ibb.co/gUOcaJ/8.jpg", "category": "nightscapes", "x": "25", "y": "25", "year": 201606, "inStock": false},
    {"url": "https://image.ibb.co/ggXENy/9.jpg", "category": "nightscapes", "x": "20", "y": "20", "year": 201608, "inStock": false},
    {"url": "https://image.ibb.co/mGBPNy/10.jpg", "category": "nightscapes", "x": "13", "y": "18", "year": 201805, "inStock": false},
    {"url": "https://image.ibb.co/cFJh9d/11.jpg", "category": "nightscapes", "x": "40", "y": "60", "year": 201704, "inStock": false},
    {"url": "https://image.ibb.co/mrVvUd/12.jpg", "category": "nightscapes", "x": "20", "y": "20", "year": 201611, "inStock": false},
    {"url": "https://image.ibb.co/itFUpd/13.jpg", "category": "nightscapes", "x": "50", "y": "60", "year": 201607, "inStock": false},
    {"url": "https://image.ibb.co/eVKYFJ/14.jpg", "category": "nightscapes", "x": "50", "y": "60", "year": 201609, "inStock": false},
    {"url": "https://image.ibb.co/dCPdhy/15.jpg", "category": "nightscapes", "x": "25", "y": "25", "year": 201612, "inStock": false},
    {"url": "https://image.ibb.co/kVp0vJ/16.jpg", "category": "other", "x": "50", "y": "60", "year": 201612, "inStock": false},
    {"url": "https://image.ibb.co/d1Wr2y/17.jpg", "category": "nightscapes", "x": "20", "y": "20", "year": 201611, "inStock": false},
    {"url": "https://image.ibb.co/eYL7aJ/18.jpg", "category": "other", "x": "60", "y": "40", "year": 201712, "inStock": false},
    {"url": "https://image.ibb.co/djXLvJ/19.jpg", "category": "flowers", "x": "50", "y": "40", "year": 201210, "inStock": false},
    {"url": "https://image.ibb.co/h4otFJ/20.jpg", "category": "nightscapes", "x": "25", "y": "25", "year": 201702, "inStock": false},
    {"url": "https://image.ibb.co/g0gfvJ/21.jpg", "category": "flowers", "x": "40", "y": "50", "year": 201304, "inStock": false},
    {"url": "https://image.ibb.co/kUy4Ny/22.jpg", "category": "landscapes", "x": "40", "y": "60", "year": 201407, "inStock": false},
    {"url": "https://image.ibb.co/euuN9d/23.jpg", "category": "landscapes", "x": "40", "y": "60", "year": 201512, "inStock": false},
    {"url": "https://image.ibb.co/irZdhy/24.jpg", "category": "flowers", "x": "30", "y": "40", "year": 201512, "inStock": false},
    {"url": "https://image.ibb.co/d5Jh9d/25.jpg", "category": "other", "x": "35", "y": "25", "year": 201512, "inStock": false},
    {"url": "https://image.ibb.co/mY1fvJ/27.jpg", "category": "landscapes", "x": "30", "y": "30", "year": 201609, "inStock": false},
    {"url": "https://image.ibb.co/h2BfvJ/28.jpg", "category": "nightscapes", "x": "20", "y": "20", "year": 201609, "inStock": false},
    {"url": "https://image.ibb.co/jq73FJ/29.jpg", "category": "nightscapes", "x": "40", "y": "30", "year": 201701, "inStock": false},
    {"url": "https://image.ibb.co/g50epd/30.jpg", "category": "nightscapes", "x": "25", "y": "25", "year": 201610, "inStock": false},
    {"url": "https://image.ibb.co/m59uNy/31.jpg", "category": "landscapes", "x": "60", "y": "50", "year": 201601, "inStock": false},
    {"url": "https://image.ibb.co/kYjThy/32.jpg", "category": "nightscapes", "x": "40", "y": "40", "year": 201611, "inStock": false},
    {"url": "https://image.ibb.co/hJJohy/33.jpg", "category": "flowers", "x": "30", "y": "50", "year": 201601, "inStock": false},
    {"url": "https://image.ibb.co/dv68hy/34.jpg", "category": "landscapes", "x": "40", "y": "40", "year": 201606, "inStock": false},
    {"url": "https://image.ibb.co/hcKThy/35.jpg", "category": "nightscapes", "x": "30", "y": "30", "year": 201609, "inStock": false},
    {"url": "https://image.ibb.co/hbYAvJ/36.jpg", "category": "flowers", "x": "80", "y": "80", "year": 201701, "inStock": false},
    {"url": "https://image.ibb.co/dFAqvJ/37.jpg", "category": "landscapes", "x": "20", "y": "20", "year": 201607, "inStock": false},
    {"url": "https://image.ibb.co/fXVZNy/38.jpg", "category": "nightscapes", "x": "30", "y": "40", "year": 201702, "inStock": false},
    {"url": "https://image.ibb.co/f9aOFJ/39.jpg", "category": "nightscapes", "x": "40", "y": "30", "year": 201705, "inStock": false},
    {"url": "https://image.ibb.co/eyb8hy/40.jpg", "category": "nightscapes", "x": "40", "y": "40", "year": 201602, "inStock": false},
    {"url": "https://image.ibb.co/efYzpd/41.jpg", "category": "nightscapes", "x": "40", "y": "40", "year": 201602, "inStock": false},
    {"url": "https://image.ibb.co/joQC9d/42.jpg", "category": "nightscapes", "x": "50", "y": "30", "year": 201607, "inStock": false},
    {"url": "https://image.ibb.co/jjZiFJ/46.jpg", "category": "nightscapes", "x": "10", "y": "10", "year": 201806, "inStock": false},
    {"url": "https://image.ibb.co/dSRxaJ/47.jpg", "category": "nightscapes", "x": "30", "y": "30", "year": 201806, "inStock": false},
    {"url": "https://image.ibb.co/nfUHaJ/48.jpg", "category": "landscapes", "x": "30", "y": "40", "year": 201806, "inStock": false},
    {"url": "https://image.ibb.co/iSjHaJ/49.jpg", "category": "nightscapes", "x": "40", "y": "40", "year": 201703, "inStock": false},
    {"url": "https://image.ibb.co/d9qC9d/50.jpg", "category": "nightscapes", "x": "20", "y": "30", "year": 201702, "inStock": false},
    {"url": "https://image.ibb.co/mUqC9d/51.jpg", "category": "nightscapes", "x": "40", "y": "30", "year": 201703, "inStock": false},
    {"url": "https://image.ibb.co/hhZHaJ/52.jpg", "category": "landscapes", "x": "30", "y": "40", "year": 201705, "inStock": false},
    {"url": "https://image.ibb.co/bJiX9d/53.jpg", "category": "nightscapes", "x": "20", "y": "20", "year": 201703, "inStock": false},
    {"url": "https://image.ibb.co/iLZuNy/54.jpg", "category": "nightscapes", "x": "6", "y": "8", "year": 201602, "inStock": false},
    {"url": "https://image.ibb.co/nMfZvJ/55.jpg", "category": "nightscapes", "x": "20", "y": "20", "year": 201806, "inStock": false},
    {"url": "https://image.ibb.co/jMH1hJ/56.jpg", "category": "flowers", "x": "50", "y": "50", "year": 201806, "inStock": false},
];

// export default urlDB;